# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16bayFkiz02AGB3I_87jqrWE0h1-1nNG-
"""

import re

def check_password_strength(password):
    # Initialize strength score
    score = 0

    # Check password length
    if len(password) >= 8:
        score += 1

    # Check for uppercase letters
    if re.search(r"[A-Z]", password):
        score += 1

    # Check for lowercase letters
    if re.search(r"[a-z]", password):
        score += 1

    # Check for digits
    if re.search(r"[0-9]", password):
        score += 1

    # Check for special characters
    if re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
        score += 1

    # Determine strength level
    if score <= 2:
        return "Weak"
    elif score == 3 or score == 4:
        return "Moderate"
    else:
        return "Strong"

# Main program
if __name__ == "__main__":
    print("🔒 Password Strength Checker 🔍")
    password = input("Enter your password: ")

    strength = check_password_strength(password)
    print(f"\nPassword Strength: {strength}")

    # Tips for improvement
    if strength == "Weak":
        print("Tip: Use at least 8 characters, mix uppercase, lowercase, numbers, and special symbols.")
    elif strength == "Moderate":
        print("Tip: Add more variety (numbers/special symbols) for stronger security.")
    else:
        print("✅ Great! Your password is strong.")
